### ISSUE TITLE
Create Reinforcement Learning Agent

### ISSUE THREAD

**Issue by paolotron** [paolotron/Drop-Hanabi#2]
create a new player based on a reinforcement learning strategy

**Comment by paolotron** [comment]
https://web.stanford.edu/class/psych209/Readings/SuttonBartoIPRLBook2ndEd.pdf is a great resource

**Comment by Alkio84** [comment]
As shown in [N. Bard et al, 2019](https://www.sciencedirect.com/science/article/pii/S0004370219300116) state-of-the-art reinforced learning algorithms are unable to compete with agents using rule-based strategies, both in self-play and ad-hoc team setting, where agents must play with unknown teammates.

**Comment by paolotron** [comment]
@Alkio84 I agree, we can drop the RL agent and concentrate on other systems
