### ISSUE TITLE
Create MCTS agent

### ISSUE THREAD

**Issue by Alkio84** [paolotron/Drop-Hanabi#6]
Create a new player based on a MCTS strategy
These are links to papers on this topic
[Re-determinizing Information Set Monte Carlo Tree Search in Hanabi](https://arxiv.org/pdf/1902.06075.pdf)
[Information Set Monte Carlo Tree Search](https://pure.york.ac.uk/portal/files/13014166/CowlingPowleyWhitehouse2012.pdf)
[Evolutionary MCTS for Multi-Action Adversarial Games](http://www.petercowling.com/wp-content/uploads/2019/02/baier2018evolutionary_cig.pdf)

The first one applies ISMCTS to hanabi, the second is the reference paper for ISMCTS and the third is another variant of MCTS that may be useful

**Comment by paolotron** [comment]
Not doable
